;; This logfile was generated automatically by `xindy'
;; at 19.11.2015  10:51:50
;; Indexstyle: "/tmp/1P0mDYxqCq", Rawindex: "/tmp/LtwU2MJX1J", Output: "main.acr"


Building indexentry-tree:
Hierdepth of index is :TREE

sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)

Forming letter-groups:
Letter-group: "¼Ú¼à" -> "N"
Letter-group: "¼Ð" -> "D"
Letter-group: "ÚÚ´" -> "T"
Letter-group: "åÈ¼" -> "V"
Letter-group: "È¨" -> "D"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "¼Ð" -> "D"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "¼Ú¼à" -> "N"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "ÚÚ´" -> "T"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "åÈ¼" -> "V"