;; This logfile was generated automatically by `xindy'
;; at 28.11.2015  17:20:32
;; Indexstyle: "/tmp/aFpxedwZVA", Rawindex: "/tmp/mmv5QFCtYF", Output: "main.acr"


Building indexentry-tree:
Hierdepth of index is :TREE

sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)

Forming letter-groups:
Letter-group: "ËË" -> "R"
Letter-group: "¼Ð" -> "D"
Letter-group: "åÈ¼" -> "V"
Letter-group: "È¨" -> "D"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "¼Ð" -> "D"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "ËË" -> "R"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "åÈ¼" -> "V"