;; This logfile was generated automatically by `xindy'
;; at 18.11.2015  15:47:22
;; Indexstyle: "/tmp/oNzW1cD9hT", Rawindex: "/tmp/2zhKwMm7jo", Output: "main.acr"


Building indexentry-tree:
Hierdepth of index is :TREE

sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)

Forming letter-groups:
Letter-group: "¼Ú¼à" -> "N"
Letter-group: "¼Ð" -> "D"
Letter-group: "ÚÚ´" -> "T"
Letter-group: "åÈ¼" -> "V"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "¼Ð" -> "D"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "¼Ú¼à" -> "N"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "ÚÚ´" -> "T"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "åÈ¼" -> "V"